// <auto-generated />
using EmployeeManager.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManager.Core.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Customer Support"
                        },
                        new
                        {
                            Id = 7,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Research and Development"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Legal"
                        });
                });

            modelBuilder.Entity("EmployeeManager.Core.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john.matthews@acme-corp.com",
                            Name = "John Matthews"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "sarah.collins@acme-corp.com",
                            Name = "Sarah Collins"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "michael.turner@acme-corp.com",
                            Name = "Michael Turner"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Email = "emily.rodriguez@acme-corp.com",
                            Name = "Emily Rodriguez"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            Email = "david.chen@acme-corp.com",
                            Name = "David Chen"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Email = "jessica.brown@acme-corp.com",
                            Name = "Jessica Brown"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            Email = "daniel.wilson@acme-corp.com",
                            Name = "Daniel Wilson"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 3,
                            Email = "olivia.martin@acme-corp.com",
                            Name = "Olivia Martin"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 4,
                            Email = "james.anderson@acme-corp.com",
                            Name = "James Anderson"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            Email = "sophia.patel@acme-corp.com",
                            Name = "Sophia Patel"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            Email = "ryan.thompson@acme-corp.com",
                            Name = "Ryan Thompson"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Email = "amanda.lewis@acme-corp.com",
                            Name = "Amanda Lewis"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            Email = "kevin.harris@acme-corp.com",
                            Name = "Kevin Harris"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 4,
                            Email = "rachel.white@acme-corp.com",
                            Name = "Rachel White"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 5,
                            Email = "brian.kim@acme-corp.com",
                            Name = "Brian Kim"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 1,
                            Email = "laura.scott@acme-corp.com",
                            Name = "Laura Scott"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 2,
                            Email = "steven.moore@acme-corp.com",
                            Name = "Steven Moore"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 3,
                            Email = "hannah.walker@acme-corp.com",
                            Name = "Hannah Walker"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 4,
                            Email = "andrew.young@acme-corp.com",
                            Name = "Andrew Young"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 5,
                            Email = "priya.nair@acme-corp.com",
                            Name = "Priya Nair"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 1,
                            Email = "mark.evans@acme-corp.com",
                            Name = "Mark Evans"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 2,
                            Email = "natalie.brooks@acme-corp.com",
                            Name = "Natalie Brooks"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 3,
                            Email = "justin.perez@acme-corp.com",
                            Name = "Justin Perez"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 4,
                            Email = "lauren.stewart@acme-corp.com",
                            Name = "Lauren Stewart"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 5,
                            Email = "arjun.mehta@acme-corp.com",
                            Name = "Arjun Mehta"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 1,
                            Email = "chris.adams@acme-corp.com",
                            Name = "Chris Adams"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 2,
                            Email = "rebecca.green@acme-corp.com",
                            Name = "Rebecca Green"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 3,
                            Email = "joshua.baker@acme-corp.com",
                            Name = "Joshua Baker"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 4,
                            Email = "megan.nelson@acme-corp.com",
                            Name = "Megan Nelson"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 5,
                            Email = "wei.zhang@acme-corp.com",
                            Name = "Wei Zhang"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 1,
                            Email = "eric.carter@acme-corp.com",
                            Name = "Eric Carter"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 2,
                            Email = "nicole.ramirez@acme-corp.com",
                            Name = "Nicole Ramirez"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 3,
                            Email = "brandon.phillips@acme-corp.com",
                            Name = "Brandon Phillips"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 4,
                            Email = "vanessa.torres@acme-corp.com",
                            Name = "Vanessa Torres"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 5,
                            Email = "ahmed.hassan@acme-corp.com",
                            Name = "Ahmed Hassan"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 1,
                            Email = "patrick.murphy@acme-corp.com",
                            Name = "Patrick Murphy"
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 2,
                            Email = "stephanie.reed@acme-corp.com",
                            Name = "Stephanie Reed"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 3,
                            Email = "anthony.cox@acme-corp.com",
                            Name = "Anthony Cox"
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 4,
                            Email = "melissa.price@acme-corp.com",
                            Name = "Melissa Price"
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 5,
                            Email = "sanjay.kulkarni@acme-corp.com",
                            Name = "Sanjay Kulkarni"
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 1,
                            Email = "adam.foster@acme-corp.com",
                            Name = "Adam Foster"
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 2,
                            Email = "julia.simmons@acme-corp.com",
                            Name = "Julia Simmons"
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 3,
                            Email = "matthew.howard@acme-corp.com",
                            Name = "Matthew Howard"
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 4,
                            Email = "danielle.long@acme-corp.com",
                            Name = "Danielle Long"
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 5,
                            Email = "omar.farooq@acme-corp.com",
                            Name = "Omar Farooq"
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 1,
                            Email = "jason.ward@acme-corp.com",
                            Name = "Jason Ward"
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 2,
                            Email = "kimberly.watson@acme-corp.com",
                            Name = "Kimberly Watson"
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 3,
                            Email = "sean.hughes@acme-corp.com",
                            Name = "Sean Hughes"
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 4,
                            Email = "tiffany.morgan@acme-corp.com",
                            Name = "Tiffany Morgan"
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 5,
                            Email = "lucas.pereira@acme-corp.com",
                            Name = "Lucas Pereira"
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 1,
                            Email = "benjamin.ortiz@acme-corp.com",
                            Name = "Benjamin Ortiz"
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 2,
                            Email = "alyssa.cooper@acme-corp.com",
                            Name = "Alyssa Cooper"
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 3,
                            Email = "noah.reed@acme-corp.com",
                            Name = "Noah Reed"
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 4,
                            Email = "katherine.bell@acme-corp.com",
                            Name = "Katherine Bell"
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 5,
                            Email = "diego.alvarez@acme-corp.com",
                            Name = "Diego Alvarez"
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 1,
                            Email = "jonathan.price@acme-corp.com",
                            Name = "Jonathan Price"
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 2,
                            Email = "monica.flores@acme-corp.com",
                            Name = "Monica Flores"
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 3,
                            Email = "caleb.russell@acme-corp.com",
                            Name = "Caleb Russell"
                        },
                        new
                        {
                            Id = 59,
                            DepartmentId = 4,
                            Email = "erica.sanders@acme-corp.com",
                            Name = "Erica Sanders"
                        },
                        new
                        {
                            Id = 60,
                            DepartmentId = 5,
                            Email = "nikhil.verma@acme-corp.com",
                            Name = "Nikhil Verma"
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 1,
                            Email = "peter.lawson@acme-corp.com",
                            Name = "Peter Lawson"
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 2,
                            Email = "grace.mitchell@acme-corp.com",
                            Name = "Grace Mitchell"
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 3,
                            Email = "aaron.bennett@acme-corp.com",
                            Name = "Aaron Bennett"
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 4,
                            Email = "lindsey.parker@acme-corp.com",
                            Name = "Lindsey Parker"
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 5,
                            Email = "yusuf.ali@acme-corp.com",
                            Name = "Yusuf Ali"
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 1,
                            Email = "george.coleman@acme-corp.com",
                            Name = "George Coleman"
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 2,
                            Email = "paige.rivera@acme-corp.com",
                            Name = "Paige Rivera"
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 3,
                            Email = "dylan.peterson@acme-corp.com",
                            Name = "Dylan Peterson"
                        },
                        new
                        {
                            Id = 69,
                            DepartmentId = 4,
                            Email = "courtney.gray@acme-corp.com",
                            Name = "Courtney Gray"
                        },
                        new
                        {
                            Id = 70,
                            DepartmentId = 5,
                            Email = "minh.nguyen@acme-corp.com",
                            Name = "Minh Nguyen"
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 1,
                            Email = "henry.powell@acme-corp.com",
                            Name = "Henry Powell"
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 2,
                            Email = "samantha.wood@acme-corp.com",
                            Name = "Samantha Wood"
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 3,
                            Email = "tyler.brooks@acme-corp.com",
                            Name = "Tyler Brooks"
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 4,
                            Email = "alexandra.kelly@acme-corp.com",
                            Name = "Alexandra Kelly"
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 5,
                            Email = "ravi.subramanian@acme-corp.com",
                            Name = "Ravi Subramanian"
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 1,
                            Email = "ethan.rogers@acme-corp.com",
                            Name = "Ethan Rogers"
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 2,
                            Email = "brittany.edwards@acme-corp.com",
                            Name = "Brittany Edwards"
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 3,
                            Email = "logan.turner@acme-corp.com",
                            Name = "Logan Turner"
                        },
                        new
                        {
                            Id = 79,
                            DepartmentId = 4,
                            Email = "madison.cruz@acme-corp.com",
                            Name = "Madison Cruz"
                        },
                        new
                        {
                            Id = 80,
                            DepartmentId = 5,
                            Email = "hiroshi.tanaka@acme-corp.com",
                            Name = "Hiroshi Tanaka"
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 1,
                            Email = "charles.fisher@acme-corp.com",
                            Name = "Charles Fisher"
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 2,
                            Email = "victoria.bennett@acme-corp.com",
                            Name = "Victoria Bennett"
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 3,
                            Email = "isaac.coleman@acme-corp.com",
                            Name = "Isaac Coleman"
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 4,
                            Email = "hailey.jenkins@acme-corp.com",
                            Name = "Hailey Jenkins"
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 5,
                            Email = "mohammed.rahman@acme-corp.com",
                            Name = "Mohammed Rahman"
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 1,
                            Email = "nathan.scott@acme-corp.com",
                            Name = "Nathan Scott"
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 2,
                            Email = "isabella.morris@acme-corp.com",
                            Name = "Isabella Morris"
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 3,
                            Email = "jordan.lee@acme-corp.com",
                            Name = "Jordan Lee"
                        },
                        new
                        {
                            Id = 89,
                            DepartmentId = 4,
                            Email = "kelsey.turner@acme-corp.com",
                            Name = "Kelsey Turner"
                        },
                        new
                        {
                            Id = 90,
                            DepartmentId = 5,
                            Email = "carlos.mendoza@acme-corp.com",
                            Name = "Carlos Mendoza"
                        },
                        new
                        {
                            Id = 91,
                            DepartmentId = 1,
                            Email = "victor.nguyen@acme-corp.com",
                            Name = "Victor Nguyen"
                        },
                        new
                        {
                            Id = 92,
                            DepartmentId = 2,
                            Email = "erin.wallace@acme-corp.com",
                            Name = "Erin Wallace"
                        },
                        new
                        {
                            Id = 93,
                            DepartmentId = 3,
                            Email = "miles.johnson@acme-corp.com",
                            Name = "Miles Johnson"
                        },
                        new
                        {
                            Id = 94,
                            DepartmentId = 4,
                            Email = "brooke.lawson@acme-corp.com",
                            Name = "Brooke Lawson"
                        },
                        new
                        {
                            Id = 95,
                            DepartmentId = 5,
                            Email = "abdul.karim@acme-corp.com",
                            Name = "Abdul Karim"
                        },
                        new
                        {
                            Id = 96,
                            DepartmentId = 1,
                            Email = "samuel.wright@acme-corp.com",
                            Name = "Samuel Wright"
                        },
                        new
                        {
                            Id = 97,
                            DepartmentId = 2,
                            Email = "chloe.martinez@acme-corp.com",
                            Name = "Chloe Martinez"
                        },
                        new
                        {
                            Id = 98,
                            DepartmentId = 3,
                            Email = "connor.hill@acme-corp.com",
                            Name = "Connor Hill"
                        },
                        new
                        {
                            Id = 99,
                            DepartmentId = 4,
                            Email = "jenna.roberts@acme-corp.com",
                            Name = "Jenna Roberts"
                        },
                        new
                        {
                            Id = 100,
                            DepartmentId = 5,
                            Email = "ibrahim.saleh@acme-corp.com",
                            Name = "Ibrahim Saleh"
                        });
                });

            modelBuilder.Entity("EmployeeManager.Core.Models.Employee", b =>
                {
                    b.HasOne("EmployeeManager.Core.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeManager.Core.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
